### ISSUE TITLE
Send subtitles to websocket without displaying in mpv

### ISSUE THREAD

**Issue by elistia** [kuroahna/mpv_websocket#5]
Apologies if this is more an MPV question..

I would like to send subtitles to a websocket but without displaying them in the mpv video output.

Currently if the subtitles are enabled, they are being sent to the websocket and I am successfully viewing them in texthooker-ui.

I understand that I must select the subtitles in mpv, otherwise if there were multiple subs available it would not know which ones to send. Is there any way to select the subtitle for mpv_websocket to use without them being displayed?
Alternatively, would there be any way to tell mpv_websocket which subs file to pick up so that it would stream the subs without them being enabled in mpv?

My use case is that most people watching the display do not want to see subtitles, but I want to display them on a separate screen that can be made visible to those that do.

Thanks.

**Comment by kuroahna** [comment]
>  Is there any way to select the subtitle for mpv_websocket to use without them being displayed?

@elistia You can hide the subtitles in mpv by pressing `v`, and still have it send the subtitles to the texthooker-ui page via websockets.

Let me know if this works for you and we can close the issue. I might also add it to the README, as this is a good use case
